# SPDX-FileCopyrightText: 2026 Deyan Paroushev
# SPDX-License-Identifier: MIT
"""
GoogleKMSSigner: Algorand signer backed by Google Cloud KMS.

The private Ed25519 key never leaves Google Cloud KMS. This signer
holds a reference to the key version resource path and uses the KMS
client to:

1. Fetch the SPKI-PEM-encoded Ed25519 public key (once, lazily, on
   first ``address`` access).
2. Derive the 58-character Algorand address from the raw 32-byte
   public key.
3. Invoke ``asymmetric_sign`` for each transaction signature.

The key never exits KMS; the operator cannot extract it. For
HSM-residency guarantees, use a key created with protection level
``HSM`` or ``HSM_SINGLE_TENANT``. GCP KMS supports four protection
levels (``SOFTWARE``, ``HSM``, ``HSM_SINGLE_TENANT``, and ``EXTERNAL``);
this signer accepts any of them, since the choice belongs to the
operator. The constructor does not currently verify the protection
level of the key version; if your compliance posture requires
HSM-residency, audit the key version configuration directly in GCP
Cloud Console. A future release may add a ``require_protection_level``
constructor parameter for callers who want this enforced
programmatically.

Optional dependency
-------------------

This module requires the ``[gcp]`` install extra::

    pip install 'actproof[gcp]'

which pulls in ``google-cloud-kms`` (the KMS client) and
``google-crc32c`` (integrity checking on KMS request/response). If
those packages are not installed, instantiating ``GoogleKMSSigner``
raises ``RuntimeError`` with the installation command.

KMS response verification (since v0.3.0)
----------------------------------------

This signer implements Google's recommended end-to-end integrity
verification for every KMS call, fail-closed on every check. The
pattern is documented in
https://cloud.google.com/kms/docs/data-integrity-guidelines and
mirrored in the official Go and Node samples at
https://cloud.google.com/kms/docs/samples/kms-sign-asymmetric. The
checks are:

For ``asymmetric_sign``:

1. ``response.name == request.name``. Detects request-name corruption
   in transit, including the wrong-key-version case where the response
   was generated by a key other than the one we addressed.
2. ``response.verified_data_crc32c is True``. KMS returns this field
   to confirm that the data CRC32C we computed and sent matched what
   it received. False (or missing) means our request was corrupted in
   transit and the signature is over the wrong bytes.
3. ``crc32c(response.signature) == response.signature_crc32c``.
   Detects response corruption in transit.
4. ``len(response.signature) == 64``. Ed25519 signatures are always 64
   octets per RFC 8032. Any other length means the response was
   corrupted or the key has the wrong algorithm.

For ``get_public_key``:

1. ``response.name == request.name``.
2. ``crc32c(response.pem.encode()) == response.pem_crc32c``.

The earlier draft used ``hasattr(response, "field") and response.field``
conditionals, which silently bypassed the check when the field was
missing or zero. v0.3.0 fails closed: every field must be present and
must satisfy the integrity invariant, or the call raises
``RuntimeError``.

Why ``data`` and not ``digest`` for Ed25519
-------------------------------------------

The KMS ``AsymmetricSignRequest`` has both a ``data`` field and a
``digest`` field. For RSA and ECDSA signing modes, callers typically
pre-hash and pass the digest. For Ed25519 in PureEdDSA mode, the
algorithm itself does the hashing as part of the signing operation, so
callers MUST pass the raw bytes via the ``data`` field. The response
field that confirms request integrity is therefore
``verified_data_crc32c`` (not ``verified_digest_crc32c``). Passing
``digest`` for an Ed25519 key returns ``INVALID_ARGUMENT`` from KMS.

Other clouds (AWS, Azure, Vault)
--------------------------------

AWS KMS does NOT support Ed25519 directly (only RSA and SEC ECC curves
P-256/P-384/P-521 plus secp256k1). AWS users with HSM-grade
requirements need either AWS CloudHSM (where Ed25519 is supported) or
an envelope-encryption pattern. Either path is out-of-scope for
actproof's bundled signers; AWS users write their own
``AlgorandSigner`` subclass against their preferred backend.

Azure Key Vault and HashiCorp Vault: write your own subclass against
their SDKs. The ``AlgorandSigner`` ABC's enforcement does the security
work regardless of backend.
"""

from __future__ import annotations

import base64
from typing import Any, Optional, Sequence, Union

from actproof.signers.interface import (
    ALGORAND_DEFAULT_MAX_FEE_MICROALGOS,
    AlgorandSigner,
    SignerValidationError,
)


__all__ = ["GoogleKMSSigner"]


# ─────────────────────────────────────────────────────────────────
# OPTIONAL IMPORTS: google-cloud-kms and google-crc32c
# ─────────────────────────────────────────────────────────────────

_INSTALL_HINT = (
    "Install with: pip install 'actproof[gcp]' "
    "(adds google-cloud-kms and google-crc32c)."
)

try:
    from google.cloud import kms_v1 as _kms_v1
    _KMS_AVAILABLE: bool = True
    _KMS_ERROR: Optional[str] = None
except Exception as exc:  # noqa: BLE001
    _KMS_AVAILABLE = False
    _KMS_ERROR = str(exc)
    _kms_v1 = None  # type: ignore[assignment,misc]

try:
    import google_crc32c as _google_crc32c
    _CRC_AVAILABLE: bool = True
    _CRC_ERROR: Optional[str] = None
except Exception as exc:  # noqa: BLE001
    _CRC_AVAILABLE = False
    _CRC_ERROR = str(exc)
    _google_crc32c = None  # type: ignore[assignment,misc]


# ─────────────────────────────────────────────────────────────────
# CONSTANTS
# ─────────────────────────────────────────────────────────────────

ALGORAND_SIGN_PREFIX: bytes = b"TX"
"""Algorand's canonical signing prefix. Every Ed25519 transaction
signature covers ``ALGORAND_SIGN_PREFIX + msgpack_encode(txn)``."""

ED25519_PUBKEY_LEN: int = 32
"""Ed25519 raw public key size in bytes (RFC 8032)."""

ED25519_SIG_LEN: int = 64
"""Ed25519 signature size in bytes (RFC 8032). Always exactly 64."""


# ─────────────────────────────────────────────────────────────────
# THE SIGNER CLASS
# ─────────────────────────────────────────────────────────────────

class GoogleKMSSigner(AlgorandSigner):
    """Algorand signer backed by Google Cloud KMS Ed25519 keys.

    The private Ed25519 key never leaves GCP KMS. For HSM-residency,
    create the key version with protection level ``HSM`` or
    ``HSM_SINGLE_TENANT``; the signer does not verify this
    programmatically (see module docstring).

    Args:
        kms_resource_name: Full resource path to the KMS Ed25519 key
            version. Example: ``projects/actproof-prod/locations/
            europe-west4/keyRings/anchoring/cryptoKeys/anchor-signer-v1/
            cryptoKeyVersions/1``.
        kms_client: Optional ``KeyManagementServiceClient`` for test
            injection. If ``None``, a default client is constructed
            using Application Default Credentials.
        allowed_note_prefixes: See ``AlgorandSigner``. Default
            ``[b"actproof:j"]``. A single ``bytes`` value is also
            accepted (e.g. ``allowed_note_prefixes=b"quoruna/v1:"``).
        max_fee_microalgos: See ``AlgorandSigner``. Default ``1000``.

    Raises:
        RuntimeError: If ``google-cloud-kms`` or ``google-crc32c`` is
            not installed (the ``[gcp]`` extra is required).
        ValueError: If ``kms_resource_name`` is not a full key-version
            path, or if ``allowed_note_prefixes`` is empty or contains
            an empty prefix, or if ``max_fee_microalgos`` is below the
            Algorand protocol minimum.
        TypeError: If ``allowed_note_prefixes`` contains a non-bytes
            element, or if ``max_fee_microalgos`` is not an int.
    """

    def __init__(
        self,
        kms_resource_name: str,
        kms_client: Optional[Any] = None,
        *,
        allowed_note_prefixes: Optional[
            Union[Sequence[bytes], bytes, bytearray]
        ] = None,
        max_fee_microalgos: int = ALGORAND_DEFAULT_MAX_FEE_MICROALGOS,
    ) -> None:
        # Initialise the policy attributes on AlgorandSigner first.
        # Invalid policy raises before we touch any KMS configuration.
        super().__init__(
            allowed_note_prefixes=allowed_note_prefixes,
            max_fee_microalgos=max_fee_microalgos,
        )

        if not _KMS_AVAILABLE:
            raise RuntimeError(
                f"google-cloud-kms is required for GoogleKMSSigner "
                f"but is not importable: {_KMS_ERROR}. {_INSTALL_HINT}"
            )
        if not _CRC_AVAILABLE:
            raise RuntimeError(
                f"google-crc32c is required for GoogleKMSSigner but "
                f"is not importable: {_CRC_ERROR}. {_INSTALL_HINT}"
            )

        if not kms_resource_name or "cryptoKeyVersions/" not in kms_resource_name:
            raise ValueError(
                f"kms_resource_name must be a full KMS key version "
                f"path (must contain 'cryptoKeyVersions/'), got "
                f"{kms_resource_name!r}"
            )

        self._kms_resource_name: str = kms_resource_name
        self._kms_client = kms_client or _kms_v1.KeyManagementServiceClient()
        self._cached_raw_pubkey: Optional[bytes] = None
        self._cached_address: Optional[str] = None

    # ─────────────────────────────────────────────────────────────
    # Public surface (the only methods the AlgorandSigner ABC allows)
    # ─────────────────────────────────────────────────────────────

    @property
    def address(self) -> str:
        """The 58-character Algorand address derived from the KMS key.

        First access triggers a KMS ``get_public_key`` call;
        subsequent accesses return the cached value.
        """
        if self._cached_address is None:
            raw_pubkey = self._fetch_raw_public_key()
            self._cached_address = _derive_algorand_address(raw_pubkey)
        return self._cached_address

    def sign_transaction(self, txn: Any) -> Any:
        """Sign an Algorand payment transaction via Google Cloud KMS.

        Args:
            txn: A ``PaymentTxn`` to sign. See
                ``AlgorandSigner.validate_transaction`` for the policy
                this enforces.

        Returns:
            An ``algosdk.transaction.SignedTransaction``.

        Raises:
            SignerValidationError: If the transaction violates the
                signing policy.
            RuntimeError: If KMS returns an error, an integrity check
                fails, or the response is malformed.
        """
        self.validate_transaction(txn)
        bytes_to_sign = self._compute_bytes_to_sign(txn)
        raw_signature = self._kms_sign(bytes_to_sign)
        return _assemble_signed_transaction(txn, raw_signature)

    # ─────────────────────────────────────────────────────────────
    # Internal: bytes-to-sign computation
    # ─────────────────────────────────────────────────────────────

    @staticmethod
    def _compute_bytes_to_sign(txn: Any) -> bytes:
        """Compute the canonical bytes that Ed25519 will sign.

        Per Algorand's signing rule::

            bytes_to_sign = b"TX" || msgpack_bytes(txn)

        ``algosdk.encoding.msgpack_encode`` returns a BASE64-ENCODED
        STRING, not raw msgpack bytes. We base64-decode to get the
        raw bytes, then prepend the TX prefix. This mirrors what
        algosdk's own ``Transaction.sign`` does internally.
        """
        try:
            from algosdk import encoding
        except Exception as exc:  # noqa: BLE001
            raise RuntimeError(
                f"py-algorand-sdk not importable: {exc}"
            ) from exc

        msgpack_b64 = encoding.msgpack_encode(txn)
        msgpack_bytes = base64.b64decode(msgpack_b64)
        return ALGORAND_SIGN_PREFIX + msgpack_bytes

    # ─────────────────────────────────────────────────────────────
    # Internal: KMS public key fetch with fail-closed integrity checks
    # ─────────────────────────────────────────────────────────────

    def _fetch_raw_public_key(self) -> bytes:
        """Fetch the SPKI-PEM-encoded Ed25519 public key from KMS,
        verify integrity end-to-end, and extract the raw 32-byte
        public key.
        """
        if self._cached_raw_pubkey is not None:
            return self._cached_raw_pubkey

        try:
            response = self._kms_client.get_public_key(
                request={"name": self._kms_resource_name}
            )
        except Exception as exc:  # noqa: BLE001
            raise RuntimeError(
                f"KMS get_public_key failed for "
                f"{self._kms_resource_name}: {exc}"
            ) from exc

        # Fail-closed: response.name must match the request name.
        response_name = getattr(response, "name", None)
        if response_name != self._kms_resource_name:
            raise RuntimeError(
                f"KMS get_public_key response.name mismatch: "
                f"expected {self._kms_resource_name!r}, got "
                f"{response_name!r}. The response may have been "
                f"corrupted in transit or generated for a different "
                f"key."
            )

        # Fail-closed: pem must be present.
        pem = getattr(response, "pem", None)
        if not pem:
            raise RuntimeError(
                "KMS get_public_key response.pem is empty or missing."
            )
        pem_bytes = pem.encode("utf-8") if isinstance(pem, str) else bytes(pem)

        # Fail-closed: pem_crc32c must be present (zero is a valid
        # CRC value; we cannot use truthiness here).
        if not hasattr(response, "pem_crc32c"):
            raise RuntimeError(
                "KMS get_public_key response missing pem_crc32c field."
            )
        try:
            expected_pem_crc = int(response.pem_crc32c)
        except (TypeError, ValueError) as exc:
            raise RuntimeError(
                f"KMS get_public_key response.pem_crc32c is not an "
                f"integer: {response.pem_crc32c!r} ({exc})"
            ) from exc
        computed_pem_crc = int(_google_crc32c.value(pem_bytes))
        if computed_pem_crc != expected_pem_crc:
            raise RuntimeError(
                f"KMS get_public_key response CRC32C mismatch: "
                f"computed {computed_pem_crc}, expected "
                f"{expected_pem_crc}. The response may have been "
                f"corrupted in transit."
            )

        raw_pubkey = _extract_raw_ed25519_from_pem(pem_bytes)
        if len(raw_pubkey) != ED25519_PUBKEY_LEN:
            raise RuntimeError(
                f"KMS returned a public key of {len(raw_pubkey)} "
                f"bytes after PEM extraction; Ed25519 public keys "
                f"are always {ED25519_PUBKEY_LEN} bytes (RFC 8032)."
            )

        self._cached_raw_pubkey = raw_pubkey
        return raw_pubkey

    # ─────────────────────────────────────────────────────────────
    # Internal: KMS asymmetric_sign with fail-closed integrity checks
    # ─────────────────────────────────────────────────────────────

    def _kms_sign(self, bytes_to_sign: bytes) -> bytes:
        """Call KMS ``asymmetric_sign`` and return the raw 64-byte
        Ed25519 signature.

        Sends ``bytes_to_sign`` as ``data``, never as ``digest``.
        Verifies all four integrity guarantees described in the module
        docstring; raises ``RuntimeError`` fail-closed on any miss.
        """
        request_crc = int(_google_crc32c.value(bytes_to_sign))

        try:
            response = self._kms_client.asymmetric_sign(
                request={
                    "name": self._kms_resource_name,
                    "data": bytes_to_sign,
                    "data_crc32c": request_crc,
                }
            )
        except Exception as exc:  # noqa: BLE001
            raise RuntimeError(
                f"KMS asymmetric_sign failed for "
                f"{self._kms_resource_name}: {exc}"
            ) from exc

        # (1) response.name must match request.name.
        response_name = getattr(response, "name", None)
        if response_name != self._kms_resource_name:
            raise RuntimeError(
                f"KMS asymmetric_sign response.name mismatch: "
                f"expected {self._kms_resource_name!r}, got "
                f"{response_name!r}. The response may have been "
                f"signed by a different key version than requested."
            )

        # (2) verified_data_crc32c must be exactly True. The
        # protobuf field is bool; we accept neither None nor missing
        # nor False.
        if not hasattr(response, "verified_data_crc32c"):
            raise RuntimeError(
                "KMS asymmetric_sign response missing "
                "verified_data_crc32c field."
            )
        if response.verified_data_crc32c is not True:
            raise RuntimeError(
                f"KMS reports request data CRC32C was not verified "
                f"(verified_data_crc32c={response.verified_data_crc32c!r}). "
                f"The signing request may have been corrupted in "
                f"transit; the signature could be over different "
                f"bytes than we sent."
            )

        # (3) signature must be present and exactly 64 bytes.
        signature = getattr(response, "signature", None)
        if not isinstance(signature, (bytes, bytearray)):
            raise RuntimeError(
                f"KMS asymmetric_sign response.signature is not "
                f"bytes: got {type(signature).__name__}."
            )
        signature_bytes = bytes(signature)
        if len(signature_bytes) != ED25519_SIG_LEN:
            raise RuntimeError(
                f"KMS asymmetric_sign returned "
                f"{len(signature_bytes)}-byte signature; Ed25519 "
                f"signatures are always {ED25519_SIG_LEN} bytes "
                f"(RFC 8032). The key version may have the wrong "
                f"algorithm."
            )

        # (4) crc32c(signature) must match signature_crc32c.
        if not hasattr(response, "signature_crc32c"):
            raise RuntimeError(
                "KMS asymmetric_sign response missing "
                "signature_crc32c field."
            )
        try:
            expected_sig_crc = int(response.signature_crc32c)
        except (TypeError, ValueError) as exc:
            raise RuntimeError(
                f"KMS asymmetric_sign response.signature_crc32c is "
                f"not an integer: {response.signature_crc32c!r} "
                f"({exc})"
            ) from exc
        computed_sig_crc = int(_google_crc32c.value(signature_bytes))
        if computed_sig_crc != expected_sig_crc:
            raise RuntimeError(
                f"KMS asymmetric_sign response signature CRC32C "
                f"mismatch: computed {computed_sig_crc}, expected "
                f"{expected_sig_crc}. The response may have been "
                f"corrupted in transit."
            )

        return signature_bytes


# ─────────────────────────────────────────────────────────────────
# HELPER: Derive Algorand address from raw Ed25519 public key
# ─────────────────────────────────────────────────────────────────

def _derive_algorand_address(raw_pubkey: bytes) -> str:
    """Derive the 58-character Algorand address from a raw Ed25519
    public key.

    The Algorand address is base32(pubkey || checksum), where the
    checksum is the last 4 bytes of SHA-512/256(pubkey). algosdk has
    the helper.
    """
    if len(raw_pubkey) != ED25519_PUBKEY_LEN:
        raise ValueError(
            f"Expected {ED25519_PUBKEY_LEN}-byte Ed25519 public key, "
            f"got {len(raw_pubkey)} bytes"
        )

    try:
        from algosdk import encoding
    except Exception as exc:  # noqa: BLE001
        raise RuntimeError(
            f"py-algorand-sdk not importable: {exc}"
        ) from exc

    return encoding.encode_address(raw_pubkey)


# ─────────────────────────────────────────────────────────────────
# HELPER: Extract raw Ed25519 public key bytes from SPKI PEM
# ─────────────────────────────────────────────────────────────────

def _extract_raw_ed25519_from_pem(pem_bytes: bytes) -> bytes:
    """Parse an SPKI-PEM-encoded Ed25519 public key and return its
    32-byte raw form.
    """
    try:
        from cryptography.hazmat.primitives.asymmetric.ed25519 import (
            Ed25519PublicKey,
        )
        from cryptography.hazmat.primitives.serialization import (
            Encoding,
            PublicFormat,
            load_pem_public_key,
        )
    except Exception as exc:  # noqa: BLE001
        raise RuntimeError(
            f"cryptography library not importable: {exc}"
        ) from exc

    pubkey = load_pem_public_key(pem_bytes)
    if not isinstance(pubkey, Ed25519PublicKey):
        raise RuntimeError(
            f"KMS returned a non-Ed25519 public key "
            f"({type(pubkey).__name__}); the key version may have "
            f"the wrong algorithm. Algorand requires Ed25519."
        )
    return pubkey.public_bytes(
        encoding=Encoding.Raw,
        format=PublicFormat.Raw,
    )


# ─────────────────────────────────────────────────────────────────
# HELPER: Assemble a SignedTransaction from txn + raw signature
# ─────────────────────────────────────────────────────────────────

def _assemble_signed_transaction(txn: Any, raw_signature: bytes) -> Any:
    """Build an ``algosdk.transaction.SignedTransaction`` from the
    transaction and the 64-byte Ed25519 signature.

    Validates the signature length before assembly. This is the last
    line of defense: even if a custom signer subclass somehow produces
    a malformed signature, this function refuses to wrap it into a
    SignedTransaction whose only failure mode would be at submission
    time, far from the bug.
    """
    if not isinstance(raw_signature, (bytes, bytearray)):
        raise RuntimeError(
            f"raw_signature must be bytes, got "
            f"{type(raw_signature).__name__}."
        )
    raw_signature_bytes = bytes(raw_signature)
    if len(raw_signature_bytes) != ED25519_SIG_LEN:
        raise RuntimeError(
            f"Ed25519 signature must be {ED25519_SIG_LEN} bytes "
            f"(RFC 8032), got {len(raw_signature_bytes)}."
        )

    try:
        from algosdk.transaction import SignedTransaction
    except Exception as exc:  # noqa: BLE001
        raise RuntimeError(
            f"py-algorand-sdk not importable: {exc}"
        ) from exc

    # algosdk's SignedTransaction expects the signature as a base64
    # string.
    signature_b64 = base64.b64encode(raw_signature_bytes).decode("ascii")
    return SignedTransaction(txn, signature_b64)
